name: Story Template
description:  Create new Cloud Operations story
title: "[gitmoji] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the fields below.
  - type: textarea
    id: user-story
    attributes:
      label: User Story
      placeholder: "As a… *[who is the user?]*  
                    I need/want/expect to… *[what does the user want to do?]*  
                    So that… *[why does the user want to do this?]*"
      value: "As a…  
              I need/want/expect to… 
              So that…"
    validations:
      required: true
  - type: textarea
    id: value-purpose
    attributes:
      description: Describe the value and purpose of the ticket.
      label: Value / Purpose
      value:
    validations:
      required: false
  - type: textarea
    id: useful-contacts
    attributes:
      description: Please add any useful contacts, these may include; Stakeholders, SME’s or 3rd Parties.
      label: Useful Contacts
      value:
    validations:
      required: false
  - type: textarea
    id: additional-information
    attributes:
      description: Please add any useful links or additional information that would be beneficial to anyone working on this Issue.
      label: Additional Information 
      value:
    validations:
      required: false
  - type: textarea
    id: dod
    attributes:
      description: Please clearly and concisely detail the DoD.
      label: Definition of Done
      value:
        Checklist for definition of done and acceptance criteria, example below (optional).

        *Example*

        - [ ] Documentation has been written / updated

        - [ ] README has been updated  

        - [ ] User docs have been updated  

        - [ ] Another team member has reviewed 

        - [ ] Tests are green
    validations:
      required: false
  - type: markdown
    id: reference
    attributes:
      label: Reference 
      value: [How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
    validations:
      required: false
